<%@ page contentType="text/html;charset=UTF-8" %>
<%@ page import="com.eduflow.servlet.FeeReceiptData" %>
<%
    FeeReceiptData receipt = (FeeReceiptData) request.getAttribute("receipt");
%>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fee Receipt - <%= receipt.studentName() %></title>
    <link rel="stylesheet" href="<%= request.getContextPath() %>/css/reports.css">
</head>
<body>
<main class="report-sheet">
    <div class="report-heading">
        <div>
            <p class="eyebrow">EduFlow Lite</p>
            <h1>Fee Receipt</h1>
        </div>
        <strong>Receipt #<%= receipt.feeId() %></strong>
    </div>
    <section class="info-grid">
        <div><span>Student</span><strong><%= receipt.studentName() %></strong></div>
        <div><span>Roll number</span><strong><%= receipt.rollNumber() %></strong></div>
        <div><span>Class</span><strong><%= receipt.className() %></strong></div>
        <div><span>Email</span><strong><%= receipt.email() %></strong></div>
    </section>
    <table>
        <tr><th>Total fee</th><td>₹ <%= receipt.totalAmount() %></td></tr>
        <tr><th>Paid amount</th><td>₹ <%= receipt.paidAmount() %></td></tr>
        <tr><th>Pending amount</th><td>₹ <%= receipt.pendingAmount() %></td></tr>
        <tr><th>Status</th><td><span class="status"><%= receipt.status() %></span></td></tr>
    </table>
    <p class="generated">Generated by EduFlow Lite</p>
    <button class="print-button" onclick="window.print()">Print receipt</button>
</main>
</body>
</html>
